<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2020-11-06T11:33:32" tests="0" file="cypress/integration/genericError.feature" failures="0" time="0">
  </testsuite>
  <testsuite name="Generic Error" timestamp="2020-11-06T11:33:32" tests="1" failures="1" time="0">
    <testcase name="Generic Error Show show the generic error when trying to create an invalid basket" time="0" classname="Show show the generic error when trying to create an invalid basket">
      <failure message="`cy.visit()` failed trying to load:

/basket?basketId=64cdef57-3ef7-4801-9faf-dd730f3edeeb

We failed looking for this file at the path:

/Users/martinegan/development/external/vodafone/web-shop-basket/basket

The internal Cypress web server responded with:

  &gt; 404: Not Found" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

/basket?basketId=64cdef57-3ef7-4801-9faf-dd730f3edeeb

We failed looking for this file at the path:

/Users/martinegan/development/external/vodafone/web-shop-basket/basket

The internal Cypress web server responded with:

  > 404: Not Found
    at http://localhost:61752/__cypress/runner/cypress_runner.js:158546:25
    at visitFailedByErr (http://localhost:61752/__cypress/runner/cypress_runner.js:157917:12)
    at http://localhost:61752/__cypress/runner/cypress_runner.js:158526:13
    at tryCatcher (http://localhost:61752/__cypress/runner/cypress_runner.js:10325:23)
    at Promise._settlePromiseFromHandler (http://localhost:61752/__cypress/runner/cypress_runner.js:8260:31)
    at Promise._settlePromise (http://localhost:61752/__cypress/runner/cypress_runner.js:8317:18)
    at Promise._settlePromise0 (http://localhost:61752/__cypress/runner/cypress_runner.js:8362:10)
    at Promise._settlePromises (http://localhost:61752/__cypress/runner/cypress_runner.js:8438:18)
    at _drainQueueStep (http://localhost:61752/__cypress/runner/cypress_runner.js:5032:12)
    at _drainQueue (http://localhost:61752/__cypress/runner/cypress_runner.js:5025:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:61752/__cypress/runner/cypress_runner.js:5041:5)
    at Async.drainQueues (http://localhost:61752/__cypress/runner/cypress_runner.js:4911:14)
From Your Spec Code:
    at _callee$ (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:295:23)
    at tryCatch (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:40087:40)
    at Generator.invoke [as _invoke] (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:40316:22)
    at Generator.prototype.<computed> [as next] (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:40139:21)
    at asyncGeneratorStep (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:398:24)
    at _next (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:420:9)
From Your Spec Code:
    at _callee$ (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:295:23)
    at tryCatch (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:40087:40)
    at Generator.invoke [as _invoke] (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:40316:22)
    at Generator.prototype.<computed> [as next] (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:40139:21)
    at asyncGeneratorStep (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:398:24)
    at _next (http://localhost:61752/__cypress/tests?p=cypress/integration/genericError.feature:420:9)]]></failure>
    </testcase>
  </testsuite>
</testsuites>